theme: practical-club-website-template
title: PHLogicians
description: Website for PHLogicians
url: "https://phlogicians.github.io"

minima:
  skin: auto
  nav_pages:
    - index.md
    - lectures.md
    - resources.md
    - ph-ormula.md

plugins:
  - jekyll-seo-tag
  - jekyll-feed

kramdown:
  math_engine: mathjax
  input: GFM

exclude:
  - README.md
  - GEMINI.md
  - _site/
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata
  - .bundle/
  - Gemfile.lock